version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    container_name: dnd-postgres
    environment:
      POSTGRES_DB: DnDAgencyDb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 52948900
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - dnd-network

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: dnd-backend
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=DnDAgencyDb;Username=postgres;Password=529489"
    ports:
      - "5000:8080"
    depends_on:
      - postgres
    networks:
      - dnd-network

  frontend:
    build:
      context: ./dnd-tavern
      dockerfile: Dockerfile
    container_name: dnd-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - dnd-network

volumes:
  postgres_data:

networks:
  dnd-network:
    driver: bridge